INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (1, 'Kiryat Eliezer Kaplan Center', 1);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (2, 'Nahal Beka Center', 2);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (3, 'Bat Galim Center', 3);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (4, 'Hadar HaCarmel Center', 4);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (5, 'Kiryat Haim Center', 5);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (6, 'Afeka Center', 6);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (7, 'Florentin Center', 7);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (8, 'Ramat aviv Center', 8);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (9, 'Bursa Center', 9);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (10, 'Shikun Vatikim Center', 10);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (11, 'Herzliya Pituah Center', 11);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (12, 'Yad Tisha Center', 12);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (13, 'Pardes Katz Center', 13);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (14, 'Azor Center', 14);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (15, 'Moledet Center', 15);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (16, 'Kiryat Eliezer Kaplan North', 1);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (17, 'Nahal Beka North', 2);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (18, 'Bat Galim North', 3);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (19, 'Hadar HaCarmel North', 4);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (20, 'Kiryat Haim North', 5);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (21, 'Afeka North', 6);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (22, 'Florentin North', 7);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (23, 'Ramat aviv North', 8);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (24, 'Bursa North', 9);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (25, 'Shikun Vatikim North', 10);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (26, 'Herzliya Pituah North', 11);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (27, 'Yad Tisha North', 12);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (28, 'Pardes Katz North', 13);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (29, 'Azor North', 14);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (30, 'Moledet North', 15);