def get_sql():
    return """INSERT INTO city (id, name, country) VALUES (1, 'Tel Aviv', 'IL');
INSERT INTO city (id, name, country) VALUES (2, 'Ramat Gan', 'IL');
INSERT INTO city (id, name, country) VALUES (3, 'Netania', 'IL');
INSERT INTO city (id, name, country) VALUES (4, 'Haifa', 'IL');
INSERT INTO city (id, name, country) VALUES (5, 'Beer Sheva', 'IL');
INSERT INTO city (id, name, country) VALUES (6, 'Hertzlia', 'IL');
INSERT INTO city (id, name, country) VALUES (7, 'Bnei Brak', 'IL');
INSERT INTO city (id, name, country) VALUES (8, 'Holon', 'IL');
INSERT INTO role (id, name) VALUES (1, 'Viewer');
INSERT INTO role (id, name) VALUES (2, 'Manager');
INSERT INTO role (id, name) VALUES (3, 'Admin');
INSERT INTO plan (id, price_per_month, allowed_items_per_month) VALUES (1, 50, 3);
INSERT INTO plan (id, price_per_month, allowed_items_per_month) VALUES (2, 100, 6);
INSERT INTO user (id, first_name, last_name, email, password, role_id) VALUES (1, 'Admin', 'Admin', 'admin@gmail.com', '$2b$12$sqHKxe1JabfqcHT1QtJ1UO53dzw6tJ/z.zrB6Y..Q3JEMWa50Oizq', 3);
INSERT INTO user (id, first_name, last_name, email, password, role_id) VALUES (2, 'Manager', 'Manager', 'manager@gmail.com', '$2b$12$H/jtPV8lupT5v5DuNPv16Oqu/wLSJpjarTo1tvp9uzOMJhvNwCu2K', 2);
INSERT INTO user (id, first_name, last_name, email, password, role_id) VALUES (3, 'Viewer', 'Viewer', 'viewer@gmail.com', '$2b$12$iyo0Ibw1noskxIg3GMyRAuIFtNJJqrTfIg9e7htYJVkOtQpnQjH/C', 1);
INSERT INTO client (id, plan_id, phone_number) VALUES (1, 1, '123456789');
INSERT INTO client (id, plan_id, phone_number) VALUES (2, 2, '987654321');
INSERT INTO client (id, plan_id, phone_number) VALUES (3, 1, '1010101010');
INSERT INTO item (id, title, description) VALUES (1, 'Screwdriver', 'The screwdriver is a humble--but mighty--addition to any tool arsenal. Although their sole purpose is all in the name, their usefulness should not be underestimated. You might never think about a screwdriver, but if you need one, you really need one.');
INSERT INTO item (id, title, description) VALUES (2, 'Hammer', 'From hanging picture frames to assembling furniture, the hammer is undoubtedly one of the most useful tools we’ve got, and it’s been that way for thousands of years. Of course, in that time, we’ve come up with more sophisticated versions (22 of them, in fact) of the crude instruments developed by our ancestors. ');
INSERT INTO item (id, title, description) VALUES (3, 'Plier', 'Pliers may date back several millennia BCE, and they continue to be one of our most versatile tools. Without them, we’d have a hard time with jewelry making, musical instrument repair, removing nails and pins, gripping hot or sharp objects, and so much more!');
INSERT INTO item (id, title, description) VALUES (4, 'Wrench', 'A wrench is used to provide grip and leverage to turn objects. ');
INSERT INTO item (id, title, description) VALUES (5, 'Level', 'The level is a perfect example of simple science. Also known as a dumpy level, builder’s level, or conveyor’s level, it consists of a long tube-like casing that is filled with a combination of air and liquid. ');
INSERT INTO item (id, title, description) VALUES (6, 'Tape Measure', 'With use cases from complex carpentry (measure twice, cut once!) to estimating how much furniture you can fit into your new home, a tape measure is a vital tool. Other applications include measuring windows for drapes and blinds, building furniture from scratch, and determining how high a picture frame or other wall decoration should be hung.');
INSERT INTO item (id, title, description) VALUES (7, 'Utility Knife', 'A version of the utility knife may have stepped onto the scene some 500,000 years ago, but the steel-bladed beauties we know today were developed in the 19th century and typically served brutish functions like butchering game and cutting wood. Bleh.');
INSERT INTO comment (id, text, item_id) VALUES (1, 'It works perfect!', 1);
INSERT INTO comment (id, text, item_id) VALUES (2, 'Very nice product', 1);
INSERT INTO comment (id, text, item_id) VALUES (3, 'Very helpful!', 2);
INSERT INTO comment (id, text, item_id) VALUES (4, 'It didn''t work!!! I''m very angry', 2);
INSERT INTO comment (id, text, item_id) VALUES (5, 'I like this product! Thanks T4U', 3);
INSERT INTO comment (id, text, item_id) VALUES (6, 'This product is broken!!! :(', 4);
INSERT INTO comment (id, text, item_id) VALUES (7, 'I didn''t used it..', 5);
INSERT INTO comment (id, text, item_id) VALUES (8, 'Wow!! I was waiting for this product for a long time!', 6);
INSERT INTO comment (id, text, item_id) VALUES (9, 'Amazing', 6);
INSERT INTO comment (id, text, item_id) VALUES (10, 'Best product ever', 7);
INSERT INTO comment (id, text, item_id) VALUES (11, 'I waited so much! Finally is at my neighboorhoud', 7);
INSERT INTO comment (id, text, item_id) VALUES (12, 'Nice', 7);
INSERT INTO comment (id, text, item_id) VALUES (13, 'Excellent', 7);
INSERT INTO comment (id, text, item_id) VALUES (14, 'Thanks!!!', 7);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (1, '2021-02-26 15:32:43.252354', 'View', 'interaction', 'Sign in', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (2, '2021-02-26 15:32:51.401914', 'View', 'interaction', 'Search', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (3, '2021-02-26 15:32:57.566611', 'View', 'interaction', 'Search', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (4, '2021-02-26 15:32:57.582525', 'View', 'interaction', 'warehouses', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (5, '2021-02-26 15:33:30.113928', 'View', 'interaction', 'Sign in', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (6, '2021-02-26 15:33:34.049516', 'View', 'interaction', 'Search', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (7, '2021-02-26 15:33:36.560751', 'View', 'interaction', 'Search', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (8, '2021-02-26 15:33:36.575084', 'View', 'interaction', 'warehouses', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (9, '2021-02-26 15:33:39.372364', 'View', 'interaction', 'confirm_order', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (10, '2021-02-26 15:33:41.650297', 'View', 'interaction', 'Search', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (11, '2021-02-26 15:33:41.661779', 'View', 'interaction', 'Search', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (12, '2021-02-26 15:33:41.668804', 'View', 'interaction', 'Search', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (13, '2021-02-26 15:34:15.073887', 'View', 'interaction', 'Sign in', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (14, '2021-02-26 15:34:51.251933', 'View', 'interaction', 'Sign in', 1);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (15, '2021-02-26 15:35:05.145648', 'View', 'interaction', 'Sign in', 2);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (16, '2021-02-26 15:35:27.564520', 'View', 'interaction', 'Analytics', 2);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (17, '2021-02-26 15:35:27.580230', 'View', 'interaction', 'Analytics', 2);
INSERT INTO event (id, timestamp, category, action, label, client_id) VALUES (18, '2021-02-26 15:59:31.134088', 'View', 'interaction', 'Sign in', 1);
INSERT INTO image (id, url, item_id) VALUES (1, 'https://cdn.shopify.com/s/files/1/0075/4178/4635/files/Screwdriver_tools_1024x1024.jpg?v=1591282638', 1);
INSERT INTO image (id, url, item_id) VALUES (2, 'https://cdn.shopify.com/s/files/1/0075/4178/4635/files/Hammer_uses_1024x1024.jpg?v=1591282666', 2);
INSERT INTO image (id, url, item_id) VALUES (3, 'https://cdn.shopify.com/s/files/1/0075/4178/4635/files/Pliers_Uses_1024x1024.jpg?v=1591282686', 3);
INSERT INTO image (id, url, item_id) VALUES (4, 'https://cdn.shopify.com/s/files/1/0075/4178/4635/files/Wrench_uses_1024x1024.jpg?v=1591282706', 4);
INSERT INTO image (id, url, item_id) VALUES (5, 'https://cdn.shopify.com/s/files/1/0075/4178/4635/files/Level_uses_1024x1024.jpg?v=1591282736', 5);
INSERT INTO image (id, url, item_id) VALUES (6, 'https://cdn.shopify.com/s/files/1/0075/4178/4635/files/Tape_measure_uses_1024x1024.jpg?v=1591282755', 6);
INSERT INTO neighbourhood (id, name, city_id) VALUES (1, 'Kiryat Eliezer Kaplan', 3);
INSERT INTO neighbourhood (id, name, city_id) VALUES (2, 'Nahal Beka', 5);
INSERT INTO neighbourhood (id, name, city_id) VALUES (3, 'Bat Galim', 4);
INSERT INTO neighbourhood (id, name, city_id) VALUES (4, 'Hadar HaCarmel', 4);
INSERT INTO neighbourhood (id, name, city_id) VALUES (5, 'Kiryat Haim', 4);
INSERT INTO neighbourhood (id, name, city_id) VALUES (6, 'Afeka', 1);
INSERT INTO neighbourhood (id, name, city_id) VALUES (7, 'Florentin', 1);
INSERT INTO neighbourhood (id, name, city_id) VALUES (8, 'Ramat aviv', 1);
INSERT INTO neighbourhood (id, name, city_id) VALUES (9, 'Bursa', 2);
INSERT INTO neighbourhood (id, name, city_id) VALUES (10, 'Shikun Vatikim', 2);
INSERT INTO neighbourhood (id, name, city_id) VALUES (11, 'Herzliya Pituah', 6);
INSERT INTO neighbourhood (id, name, city_id) VALUES (12, 'Yad Tisha', 6);
INSERT INTO neighbourhood (id, name, city_id) VALUES (13, 'Pardes Katz', 7);
INSERT INTO neighbourhood (id, name, city_id) VALUES (14, 'Azor', 8);
INSERT INTO neighbourhood (id, name, city_id) VALUES (15, 'Moledet', 8);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (1, 'Kiryat Eliezer Kaplan Center', 1);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (2, 'Nahal Beka Center', 2);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (3, 'Bat Galim Center', 3);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (4, 'Hadar HaCarmel Center', 4);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (5, 'Kiryat Haim Center', 5);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (6, 'Afeka Center', 6);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (7, 'Florentin Center', 7);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (8, 'Ramat aviv Center', 8);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (9, 'Bursa Center', 9);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (10, 'Shikun Vatikim Center', 10);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (11, 'Herzliya Pituah Center', 11);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (12, 'Yad Tisha Center', 12);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (13, 'Pardes Katz Center', 13);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (14, 'Azor Center', 14);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (15, 'Moledet Center', 15);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (16, 'Kiryat Eliezer Kaplan North', 1);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (17, 'Nahal Beka North', 2);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (18, 'Bat Galim North', 3);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (19, 'Hadar HaCarmel North', 4);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (20, 'Kiryat Haim North', 5);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (21, 'Afeka North', 6);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (22, 'Florentin North', 7);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (23, 'Ramat aviv North', 8);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (24, 'Bursa North', 9);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (25, 'Shikun Vatikim North', 10);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (26, 'Herzliya Pituah North', 11);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (27, 'Yad Tisha North', 12);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (28, 'Pardes Katz North', 13);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (29, 'Azor North', 14);
INSERT INTO warehouse (id, name, neighbourhood_id) VALUES (30, 'Moledet North', 15);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (1, 'Sderot Ben Gurion', 12, '32.0825873', '34.7801409', 1);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (2, 'Bialik', 148, '32.088989', '34.8004513', 2);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (3, 'David Hamelech', 43, '32.3346471', '34.8499245', 3);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (4, 'Shalom Aleichem', 101, '32.7801936', '35.0162554', 4);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (5, 'Derech Metsada', 18, '31.258839', '34.7880506', 5);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (6, 'Yaakov Dori', 3, '31.2675', '34.7821624', 5);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (7, 'Menachem Begin', 121, '32.1760902', '34.8294727', 6);
INSERT INTO location (id, address_street, address_number, latitude, longitude, warehouse_id) VALUES (8, 'HaMeginim', 98, '32.1730528', '34.8084663', 6);
INSERT INTO "order" (id, client_id, item_id, warehouse_id, start_date, end_date) VALUES (1, 1, 2, 6, '2021-02-26 15:33:40.795477', null);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (1, 1, 1);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (2, 1, 2);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (3, 1, 3);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (4, 1, 13);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (5, 1, 14);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (6, 2, 2);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (7, 2, 3);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (8, 3, 3);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (9, 3, 4);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (10, 4, 4);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (11, 4, 5);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (12, 5, 5);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (13, 5, 6);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (14, 6, 6);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (15, 6, 7);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (16, 7, 1);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (17, 7, 7);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (18, 8, 1);
INSERT INTO warehouse_items (warehouse_id, item_id, count) VALUES (19, 8, 2);
"""